#!/bin/bash
#Author:Zhangtao
#Date & Time: 2016-02-15-22:06:56
#Description:Automatically create some datas

for i in {11..35}
do
    value=$[ $i % 5 ]
    if [ $value -eq 0 ]
    then
        echo -n "data$i. " >> data1
        echo >> data1
    else
        echo -n "data$i. " >> data1
    fi
    
done

#gawk 'BEGIN{FS="."}{print $1,$2,$3}''
#Result:
#data11. data12. data13. data14. data15. 
#data16. data17. data18. data19. data20. 
#data21. data22. data23. data24. data25. 
#data26. data27. data28. data29. data30. 
#data31. data32. data33. data34. data35. 

#gawk 'BEGIN{FS=".";OFS="<-->"}{print $1,$2,$3}' data1
#Result:
#data11<--> data12<--> data13
#data16<--> data17<--> data18
#data21<--> data22<--> data23
#data26<--> data27<--> data28
#data31<--> data32<--> data33
#
