#!/bin/bash
#Author:Zhangtao
#Date & Time: 2016-02-17-16:13:12
#Description:
for i in {1..10}
do
    echo -n "Number$i    " >> $1
done
echo >> $1

for i in {1..1000}
do
    echo -n "$RANDOM    " >> $1
    if [ $[ $i % 10 ] -eq 0 ]
    then
        echo >> $1
    fi
done
