#!/bin/bash
#Author:Zhangtao
#Date & Time: 2016-02-28-16:05:56
#Description:sending the current disk statistics in an e-mail message
date=`date  "+%m%d%Y"`
MAIL=`which mail`
TEMP=`mktemp tmp.XXXXXX`

df -k > $TEMP
cat $TEMP | $MAIL -s "Disk stats for $date" $1
rm -f $TEMP
