#!/bin/bash
#Author:Zhangtao
#Date & Time: 2016-01-20-22:34:18
#Description:Testing BEGIN and END
BEGIN {
print "The latest list of users and shells"
print "Userid      Shell"
print "------      ------"
FS=":"
}

{
    print $1 "      " $7
}

END {
print "This concludes the listing"
}
