#!/bin/bash
#Author:Zhangtao
#Date & Time: 2016-02-28-15:52:21
#Description:mailing the answer to a factorial
number=1
result=1
MAIL=`which mail`
read -p "Input a number:" value
while [ $number -le $value ]
do
    result=$[ $result * $number ]
    number=$[ $number + 1 ]
done

echo "Result is $result" | $MAIL -s "factorial" $USER

